// <auto-generated />
using System;
using BrokerServices.common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BrokerServices.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20191016011416_CorregirTipoLlavePrimaria")]
    partial class CorregirTipoLlavePrimaria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EntityModelFundabien.entities.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.HasKey("AutorId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Correo", b =>
                {
                    b.Property<long>("idCorreo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("correo");

                    b.Property<bool>("estaHabilitado");

                    b.Property<DateTime>("fechaRegistro");

                    b.Property<long?>("personaidPersona");

                    b.HasKey("idCorreo");

                    b.HasIndex("personaidPersona");

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Departamento", b =>
                {
                    b.Property<long>("idDepartamento")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("idPais");

                    b.Property<string>("nombre");

                    b.HasKey("idDepartamento");

                    b.HasIndex("idPais");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            idDepartamento = 1L,
                            idPais = 1L,
                            nombre = "Alta Verapaz"
                        },
                        new
                        {
                            idDepartamento = 2L,
                            idPais = 1L,
                            nombre = "Baja Verapaz"
                        },
                        new
                        {
                            idDepartamento = 3L,
                            idPais = 1L,
                            nombre = "Chimaltenango"
                        },
                        new
                        {
                            idDepartamento = 4L,
                            idPais = 1L,
                            nombre = "Chiquimula"
                        },
                        new
                        {
                            idDepartamento = 5L,
                            idPais = 1L,
                            nombre = "El Progreso"
                        },
                        new
                        {
                            idDepartamento = 6L,
                            idPais = 1L,
                            nombre = "Escuintla"
                        },
                        new
                        {
                            idDepartamento = 7L,
                            idPais = 1L,
                            nombre = "Guatemala"
                        },
                        new
                        {
                            idDepartamento = 8L,
                            idPais = 1L,
                            nombre = "Huehuetenango"
                        },
                        new
                        {
                            idDepartamento = 9L,
                            idPais = 1L,
                            nombre = "Izabal"
                        },
                        new
                        {
                            idDepartamento = 10L,
                            idPais = 1L,
                            nombre = "Jutiapa"
                        },
                        new
                        {
                            idDepartamento = 11L,
                            idPais = 1L,
                            nombre = "Petén"
                        },
                        new
                        {
                            idDepartamento = 12L,
                            idPais = 1L,
                            nombre = "Quetzaltenango"
                        },
                        new
                        {
                            idDepartamento = 13L,
                            idPais = 1L,
                            nombre = "Quiché"
                        },
                        new
                        {
                            idDepartamento = 14L,
                            idPais = 1L,
                            nombre = "Retalhuleu"
                        },
                        new
                        {
                            idDepartamento = 15L,
                            idPais = 1L,
                            nombre = "Sacatepéquez"
                        },
                        new
                        {
                            idDepartamento = 16L,
                            idPais = 1L,
                            nombre = "San Marcos"
                        },
                        new
                        {
                            idDepartamento = 17L,
                            idPais = 1L,
                            nombre = "Santa Rosa"
                        },
                        new
                        {
                            idDepartamento = 18L,
                            idPais = 1L,
                            nombre = "Sololá"
                        },
                        new
                        {
                            idDepartamento = 19L,
                            idPais = 1L,
                            nombre = "Suchitepéquez"
                        },
                        new
                        {
                            idDepartamento = 20L,
                            idPais = 1L,
                            nombre = "Totonicapán"
                        },
                        new
                        {
                            idDepartamento = 21L,
                            idPais = 1L,
                            nombre = "Zacapa"
                        },
                        new
                        {
                            idDepartamento = 22L,
                            idPais = 1L,
                            nombre = "Jalapa"
                        });
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Direccion", b =>
                {
                    b.Property<long>("idDireccion")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descripcion");

                    b.Property<long>("idMunicipio");

                    b.HasKey("idDireccion");

                    b.HasIndex("idMunicipio");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Municipio", b =>
                {
                    b.Property<long>("idMunicipio")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("idDepartamento");

                    b.Property<string>("nombre");

                    b.HasKey("idMunicipio");

                    b.HasIndex("idDepartamento");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Paciente", b =>
                {
                    b.Property<long>("idPaciente")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("estaActivo");

                    b.Property<long>("historialClinico");

                    b.Property<long>("idPersona");

                    b.HasKey("idPaciente");

                    b.HasIndex("idPersona");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Pais", b =>
                {
                    b.Property<long>("idPais")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombre");

                    b.HasKey("idPais");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            idPais = 1L,
                            nombre = "Guatemala"
                        });
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Persona", b =>
                {
                    b.Property<long>("idPersona")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("escolaridad");

                    b.Property<DateTime>("fechaNacimiento");

                    b.Property<string>("grupoEtnico");

                    b.Property<long>("idDomicilio");

                    b.Property<long>("idResidencia");

                    b.Property<string>("primerApellido");

                    b.Property<string>("primerNombre");

                    b.Property<string>("religion");

                    b.Property<string>("segundoApellido");

                    b.Property<string>("segundoNombre");

                    b.Property<bool>("sexo");

                    b.HasKey("idPersona");

                    b.HasIndex("idDomicilio");

                    b.HasIndex("idResidencia");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.PersonaEncargada", b =>
                {
                    b.Property<long>("idPersonaEncargada")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("estaActivo");

                    b.Property<long>("idPaciente");

                    b.Property<long>("idPersona");

                    b.Property<string>("parentezco");

                    b.HasKey("idPersonaEncargada");

                    b.HasIndex("idPaciente");

                    b.HasIndex("idPersona");

                    b.ToTable("PersonasEncargadas");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.RegistroMedico", b =>
                {
                    b.Property<long>("idRegistroMedico")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("estaFirmado");

                    b.Property<DateTime>("fechaAdmision");

                    b.Property<long>("idPaciente");

                    b.HasKey("idRegistroMedico");

                    b.HasIndex("idPaciente");

                    b.ToTable("RegistrosMedicos");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.RegistroMedicoDiagnostico", b =>
                {
                    b.Property<long>("idRegistroMedicoDiagnostico")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("diagnosticoFinal");

                    b.Property<long>("idRegistroMedico");

                    b.Property<string>("recomendaciones");

                    b.HasKey("idRegistroMedicoDiagnostico");

                    b.HasIndex("idRegistroMedico");

                    b.ToTable("RegistrosMedicosDiagnostico");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Telefono", b =>
                {
                    b.Property<long>("idTelefono")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("estaHabilitado");

                    b.Property<DateTime>("fechaRegistro");

                    b.Property<long>("idPersona");

                    b.Property<string>("telefono");

                    b.HasKey("idTelefono");

                    b.HasIndex("idPersona");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Correo", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaidPersona");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Departamento", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Pais", "pais")
                        .WithMany("departamentos")
                        .HasForeignKey("idPais")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Direccion", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Municipio", "municipio")
                        .WithMany("direcciones")
                        .HasForeignKey("idMunicipio")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Municipio", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Departamento")
                        .WithMany("municipios")
                        .HasForeignKey("idDepartamento")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Paciente", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("idPersona")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Persona", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Direccion", "domicilio")
                        .WithMany()
                        .HasForeignKey("idDomicilio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityModelFundabien.entities.Direccion", "residencia")
                        .WithMany()
                        .HasForeignKey("idResidencia")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.PersonaEncargada", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityModelFundabien.entities.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("idPersona")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.RegistroMedico", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Paciente", "paciente")
                        .WithMany("registrosMedicos")
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.RegistroMedicoDiagnostico", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.RegistroMedico", "registroMedico")
                        .WithMany()
                        .HasForeignKey("idRegistroMedico")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Telefono", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("idPersona")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
