// <auto-generated />
using System;
using BrokerServices.common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BrokerServices.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20191009052510_Mun")]
    partial class Mun
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EntityModelFundabien.entities.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.HasKey("AutorId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Correo", b =>
                {
                    b.Property<double>("idCorreo");

                    b.Property<string>("correo");

                    b.Property<bool>("estaHabilitado");

                    b.Property<DateTime>("fechaRegistro");

                    b.Property<double?>("personaidPersona");

                    b.HasKey("idCorreo");

                    b.HasIndex("personaidPersona");

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Departamento", b =>
                {
                    b.Property<double>("idDepartamento");

                    b.Property<double>("idPais");

                    b.Property<string>("nombre");

                    b.HasKey("idDepartamento");

                    b.HasIndex("idPais");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            idDepartamento = 1.0,
                            idPais = 1.0,
                            nombre = "Alta Verapaz"
                        },
                        new
                        {
                            idDepartamento = 2.0,
                            idPais = 1.0,
                            nombre = "Baja Verapaz"
                        },
                        new
                        {
                            idDepartamento = 3.0,
                            idPais = 1.0,
                            nombre = "Chimaltenango"
                        },
                        new
                        {
                            idDepartamento = 4.0,
                            idPais = 1.0,
                            nombre = "Chiquimula"
                        },
                        new
                        {
                            idDepartamento = 5.0,
                            idPais = 1.0,
                            nombre = "El Progreso"
                        },
                        new
                        {
                            idDepartamento = 6.0,
                            idPais = 1.0,
                            nombre = "Escuintla"
                        },
                        new
                        {
                            idDepartamento = 7.0,
                            idPais = 1.0,
                            nombre = "Guatemala"
                        },
                        new
                        {
                            idDepartamento = 8.0,
                            idPais = 1.0,
                            nombre = "Huehuetenango"
                        },
                        new
                        {
                            idDepartamento = 9.0,
                            idPais = 1.0,
                            nombre = "Izabal"
                        },
                        new
                        {
                            idDepartamento = 10.0,
                            idPais = 1.0,
                            nombre = "Jutiapa"
                        },
                        new
                        {
                            idDepartamento = 11.0,
                            idPais = 1.0,
                            nombre = "Petén"
                        },
                        new
                        {
                            idDepartamento = 12.0,
                            idPais = 1.0,
                            nombre = "Quetzaltenango"
                        },
                        new
                        {
                            idDepartamento = 13.0,
                            idPais = 1.0,
                            nombre = "Quiché"
                        },
                        new
                        {
                            idDepartamento = 14.0,
                            idPais = 1.0,
                            nombre = "Retalhuleu"
                        },
                        new
                        {
                            idDepartamento = 15.0,
                            idPais = 1.0,
                            nombre = "Sacatepéquez"
                        },
                        new
                        {
                            idDepartamento = 16.0,
                            idPais = 1.0,
                            nombre = "San Marcos"
                        },
                        new
                        {
                            idDepartamento = 17.0,
                            idPais = 1.0,
                            nombre = "Santa Rosa"
                        },
                        new
                        {
                            idDepartamento = 18.0,
                            idPais = 1.0,
                            nombre = "Sololá"
                        },
                        new
                        {
                            idDepartamento = 19.0,
                            idPais = 1.0,
                            nombre = "Suchitepéquez"
                        },
                        new
                        {
                            idDepartamento = 20.0,
                            idPais = 1.0,
                            nombre = "Totonicapán"
                        },
                        new
                        {
                            idDepartamento = 21.0,
                            idPais = 1.0,
                            nombre = "Zacapa"
                        },
                        new
                        {
                            idDepartamento = 22.0,
                            idPais = 1.0,
                            nombre = "Jalapa"
                        });
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Direccion", b =>
                {
                    b.Property<double>("idDireccion");

                    b.Property<string>("descripcion");

                    b.Property<double>("idMunicipio");

                    b.HasKey("idDireccion");

                    b.HasIndex("idMunicipio");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Municipio", b =>
                {
                    b.Property<double>("idMunicipio");

                    b.Property<double>("idDepartamento");

                    b.Property<string>("nombre");

                    b.HasKey("idMunicipio");

                    b.HasIndex("idDepartamento");

                    b.ToTable("Municipios");

                    b.HasData(
                        new
                        {
                            idMunicipio = 1.0,
                            idDepartamento = 1.0,
                            nombre = "Cahabón"
                        },
                        new
                        {
                            idMunicipio = 2.0,
                            idDepartamento = 1.0,
                            nombre = "Chahal"
                        },
                        new
                        {
                            idMunicipio = 3.0,
                            idDepartamento = 1.0,
                            nombre = "Chisec"
                        },
                        new
                        {
                            idMunicipio = 4.0,
                            idDepartamento = 1.0,
                            nombre = "Cobán"
                        },
                        new
                        {
                            idMunicipio = 5.0,
                            idDepartamento = 1.0,
                            nombre = "Fray Bartolomé de las Casas"
                        },
                        new
                        {
                            idMunicipio = 6.0,
                            idDepartamento = 1.0,
                            nombre = "Lanquín"
                        },
                        new
                        {
                            idMunicipio = 7.0,
                            idDepartamento = 1.0,
                            nombre = "Panzós"
                        },
                        new
                        {
                            idMunicipio = 8.0,
                            idDepartamento = 1.0,
                            nombre = "Raxruha"
                        },
                        new
                        {
                            idMunicipio = 9.0,
                            idDepartamento = 1.0,
                            nombre = "San Cristóbal Verapaz"
                        },
                        new
                        {
                            idMunicipio = 10.0,
                            idDepartamento = 1.0,
                            nombre = "San Juan Chamelco"
                        },
                        new
                        {
                            idMunicipio = 11.0,
                            idDepartamento = 1.0,
                            nombre = "San Pedro Carchá"
                        },
                        new
                        {
                            idMunicipio = 12.0,
                            idDepartamento = 1.0,
                            nombre = "Santa Cruz Verapaz"
                        },
                        new
                        {
                            idMunicipio = 13.0,
                            idDepartamento = 1.0,
                            nombre = "Senahú"
                        },
                        new
                        {
                            idMunicipio = 14.0,
                            idDepartamento = 1.0,
                            nombre = "Tactic"
                        },
                        new
                        {
                            idMunicipio = 15.0,
                            idDepartamento = 1.0,
                            nombre = "Tamahú"
                        },
                        new
                        {
                            idMunicipio = 16.0,
                            idDepartamento = 1.0,
                            nombre = "Tucurú"
                        },
                        new
                        {
                            idMunicipio = 17.0,
                            idDepartamento = 1.0,
                            nombre = "Santa Catarina La Tinta"
                        },
                        new
                        {
                            idMunicipio = 18.0,
                            idDepartamento = 2.0,
                            nombre = "Cubulco"
                        },
                        new
                        {
                            idMunicipio = 19.0,
                            idDepartamento = 2.0,
                            nombre = "Granados"
                        },
                        new
                        {
                            idMunicipio = 20.0,
                            idDepartamento = 2.0,
                            nombre = "Purulhá"
                        },
                        new
                        {
                            idMunicipio = 21.0,
                            idDepartamento = 2.0,
                            nombre = "Rabinal"
                        },
                        new
                        {
                            idMunicipio = 22.0,
                            idDepartamento = 2.0,
                            nombre = "Salamá"
                        },
                        new
                        {
                            idMunicipio = 23.0,
                            idDepartamento = 2.0,
                            nombre = "San Jerónimo"
                        },
                        new
                        {
                            idMunicipio = 24.0,
                            idDepartamento = 2.0,
                            nombre = "San Miguel Chicaj"
                        },
                        new
                        {
                            idMunicipio = 25.0,
                            idDepartamento = 2.0,
                            nombre = "Santa Cruz El Chol"
                        },
                        new
                        {
                            idMunicipio = 26.0,
                            idDepartamento = 3.0,
                            nombre = "Acatenango"
                        },
                        new
                        {
                            idMunicipio = 27.0,
                            idDepartamento = 3.0,
                            nombre = "Chimaltenango"
                        },
                        new
                        {
                            idMunicipio = 28.0,
                            idDepartamento = 3.0,
                            nombre = "El Tejar"
                        },
                        new
                        {
                            idMunicipio = 29.0,
                            idDepartamento = 3.0,
                            nombre = "Parramos"
                        },
                        new
                        {
                            idMunicipio = 30.0,
                            idDepartamento = 3.0,
                            nombre = "Patzicía"
                        },
                        new
                        {
                            idMunicipio = 31.0,
                            idDepartamento = 3.0,
                            nombre = "Patzún"
                        },
                        new
                        {
                            idMunicipio = 32.0,
                            idDepartamento = 3.0,
                            nombre = "Pochuta"
                        },
                        new
                        {
                            idMunicipio = 33.0,
                            idDepartamento = 3.0,
                            nombre = "San Andrés Itzapa"
                        },
                        new
                        {
                            idMunicipio = 34.0,
                            idDepartamento = 3.0,
                            nombre = "San José Poaquil"
                        },
                        new
                        {
                            idMunicipio = 35.0,
                            idDepartamento = 3.0,
                            nombre = "San Juan Comalapa"
                        },
                        new
                        {
                            idMunicipio = 36.0,
                            idDepartamento = 3.0,
                            nombre = "San Martín Jilotepeque"
                        },
                        new
                        {
                            idMunicipio = 37.0,
                            idDepartamento = 3.0,
                            nombre = "Santa Apolonia"
                        },
                        new
                        {
                            idMunicipio = 38.0,
                            idDepartamento = 3.0,
                            nombre = "Santa Cruz Balanyá"
                        },
                        new
                        {
                            idMunicipio = 39.0,
                            idDepartamento = 3.0,
                            nombre = "Tecpán Guatemala"
                        },
                        new
                        {
                            idMunicipio = 40.0,
                            idDepartamento = 3.0,
                            nombre = "Yepocapa"
                        },
                        new
                        {
                            idMunicipio = 41.0,
                            idDepartamento = 3.0,
                            nombre = "Zaragoza"
                        },
                        new
                        {
                            idMunicipio = 42.0,
                            idDepartamento = 4.0,
                            nombre = "Camotán"
                        },
                        new
                        {
                            idMunicipio = 43.0,
                            idDepartamento = 4.0,
                            nombre = "Chiquimula"
                        },
                        new
                        {
                            idMunicipio = 44.0,
                            idDepartamento = 4.0,
                            nombre = "Concepción Las Minas"
                        },
                        new
                        {
                            idMunicipio = 45.0,
                            idDepartamento = 4.0,
                            nombre = "Esquipulas"
                        },
                        new
                        {
                            idMunicipio = 46.0,
                            idDepartamento = 4.0,
                            nombre = "Ipala"
                        },
                        new
                        {
                            idMunicipio = 47.0,
                            idDepartamento = 4.0,
                            nombre = "Jocotán"
                        },
                        new
                        {
                            idMunicipio = 48.0,
                            idDepartamento = 4.0,
                            nombre = "Olopa"
                        },
                        new
                        {
                            idMunicipio = 49.0,
                            idDepartamento = 4.0,
                            nombre = "Quezaltepeque"
                        },
                        new
                        {
                            idMunicipio = 50.0,
                            idDepartamento = 4.0,
                            nombre = "San Jacinto"
                        },
                        new
                        {
                            idMunicipio = 51.0,
                            idDepartamento = 4.0,
                            nombre = "San José La Arada"
                        },
                        new
                        {
                            idMunicipio = 52.0,
                            idDepartamento = 4.0,
                            nombre = "San Juan Ermita"
                        },
                        new
                        {
                            idMunicipio = 53.0,
                            idDepartamento = 5.0,
                            nombre = "El Jícaro"
                        },
                        new
                        {
                            idMunicipio = 54.0,
                            idDepartamento = 5.0,
                            nombre = "Guastatoya"
                        },
                        new
                        {
                            idMunicipio = 55.0,
                            idDepartamento = 5.0,
                            nombre = "Morazán"
                        },
                        new
                        {
                            idMunicipio = 56.0,
                            idDepartamento = 5.0,
                            nombre = "San Agustín Acasaguastlán"
                        },
                        new
                        {
                            idMunicipio = 57.0,
                            idDepartamento = 5.0,
                            nombre = "San Antonio La Paz"
                        },
                        new
                        {
                            idMunicipio = 58.0,
                            idDepartamento = 5.0,
                            nombre = "San Cristóbal Acasaguastlán"
                        },
                        new
                        {
                            idMunicipio = 59.0,
                            idDepartamento = 5.0,
                            nombre = "Sanarate"
                        },
                        new
                        {
                            idMunicipio = 60.0,
                            idDepartamento = 6.0,
                            nombre = "Escuintla"
                        },
                        new
                        {
                            idMunicipio = 61.0,
                            idDepartamento = 6.0,
                            nombre = "Iztapa"
                        },
                        new
                        {
                            idMunicipio = 62.0,
                            idDepartamento = 6.0,
                            nombre = "La Democracia"
                        },
                        new
                        {
                            idMunicipio = 63.0,
                            idDepartamento = 6.0,
                            nombre = "La Gomera"
                        },
                        new
                        {
                            idMunicipio = 64.0,
                            idDepartamento = 6.0,
                            nombre = "Masagua"
                        },
                        new
                        {
                            idMunicipio = 65.0,
                            idDepartamento = 6.0,
                            nombre = "Nueva Concepción"
                        },
                        new
                        {
                            idMunicipio = 66.0,
                            idDepartamento = 6.0,
                            nombre = "Palín"
                        },
                        new
                        {
                            idMunicipio = 67.0,
                            idDepartamento = 6.0,
                            nombre = "San José"
                        },
                        new
                        {
                            idMunicipio = 68.0,
                            idDepartamento = 6.0,
                            nombre = "San Vicente Pacaya"
                        },
                        new
                        {
                            idMunicipio = 69.0,
                            idDepartamento = 6.0,
                            nombre = "Santa Lucía Cotzumalguapa"
                        },
                        new
                        {
                            idMunicipio = 70.0,
                            idDepartamento = 6.0,
                            nombre = "Siquinalá"
                        },
                        new
                        {
                            idMunicipio = 71.0,
                            idDepartamento = 6.0,
                            nombre = "Tiquisate"
                        },
                        new
                        {
                            idMunicipio = 72.0,
                            idDepartamento = 7.0,
                            nombre = "Amatitlán"
                        },
                        new
                        {
                            idMunicipio = 73.0,
                            idDepartamento = 7.0,
                            nombre = "Chinautla"
                        },
                        new
                        {
                            idMunicipio = 74.0,
                            idDepartamento = 7.0,
                            nombre = "Chuarrancho"
                        },
                        new
                        {
                            idMunicipio = 75.0,
                            idDepartamento = 7.0,
                            nombre = "Fraijanes"
                        },
                        new
                        {
                            idMunicipio = 76.0,
                            idDepartamento = 7.0,
                            nombre = "Guatemala"
                        },
                        new
                        {
                            idMunicipio = 77.0,
                            idDepartamento = 7.0,
                            nombre = "Mixco"
                        },
                        new
                        {
                            idMunicipio = 78.0,
                            idDepartamento = 7.0,
                            nombre = "Palencia"
                        },
                        new
                        {
                            idMunicipio = 79.0,
                            idDepartamento = 7.0,
                            nombre = "San Miguel Petapa"
                        },
                        new
                        {
                            idMunicipio = 80.0,
                            idDepartamento = 7.0,
                            nombre = "San José del Golfo"
                        },
                        new
                        {
                            idMunicipio = 81.0,
                            idDepartamento = 7.0,
                            nombre = "San José Pinula"
                        },
                        new
                        {
                            idMunicipio = 82.0,
                            idDepartamento = 7.0,
                            nombre = "San Juan Sacatepéquez"
                        },
                        new
                        {
                            idMunicipio = 83.0,
                            idDepartamento = 7.0,
                            nombre = "San Pedro Ayampuc"
                        },
                        new
                        {
                            idMunicipio = 84.0,
                            idDepartamento = 7.0,
                            nombre = "San Pedro Sacatepéquez"
                        },
                        new
                        {
                            idMunicipio = 85.0,
                            idDepartamento = 7.0,
                            nombre = "San Raymundo"
                        },
                        new
                        {
                            idMunicipio = 86.0,
                            idDepartamento = 7.0,
                            nombre = "Santa Catarina Pinula"
                        },
                        new
                        {
                            idMunicipio = 87.0,
                            idDepartamento = 7.0,
                            nombre = "Villa Canales"
                        },
                        new
                        {
                            idMunicipio = 88.0,
                            idDepartamento = 8.0,
                            nombre = "Aguacatán"
                        },
                        new
                        {
                            idMunicipio = 89.0,
                            idDepartamento = 8.0,
                            nombre = "Chiantla"
                        },
                        new
                        {
                            idMunicipio = 90.0,
                            idDepartamento = 8.0,
                            nombre = "Colotenango"
                        },
                        new
                        {
                            idMunicipio = 91.0,
                            idDepartamento = 8.0,
                            nombre = "Concepción Huista"
                        },
                        new
                        {
                            idMunicipio = 92.0,
                            idDepartamento = 8.0,
                            nombre = "Cuilco"
                        },
                        new
                        {
                            idMunicipio = 93.0,
                            idDepartamento = 8.0,
                            nombre = "Huehuetenango"
                        },
                        new
                        {
                            idMunicipio = 94.0,
                            idDepartamento = 8.0,
                            nombre = "Ixtahuacán"
                        },
                        new
                        {
                            idMunicipio = 95.0,
                            idDepartamento = 8.0,
                            nombre = "Jacaltenango"
                        },
                        new
                        {
                            idMunicipio = 96.0,
                            idDepartamento = 8.0,
                            nombre = "La Democracia"
                        },
                        new
                        {
                            idMunicipio = 97.0,
                            idDepartamento = 8.0,
                            nombre = "La Libertad"
                        },
                        new
                        {
                            idMunicipio = 98.0,
                            idDepartamento = 8.0,
                            nombre = "Malacatancito"
                        },
                        new
                        {
                            idMunicipio = 99.0,
                            idDepartamento = 8.0,
                            nombre = "Nentón"
                        },
                        new
                        {
                            idMunicipio = 100.0,
                            idDepartamento = 8.0,
                            nombre = "San Antonio Huista"
                        },
                        new
                        {
                            idMunicipio = 101.0,
                            idDepartamento = 8.0,
                            nombre = "San Gaspar Ixchil"
                        },
                        new
                        {
                            idMunicipio = 102.0,
                            idDepartamento = 8.0,
                            nombre = "San Juan Atitán"
                        },
                        new
                        {
                            idMunicipio = 103.0,
                            idDepartamento = 8.0,
                            nombre = "San Juan Ixcoy"
                        },
                        new
                        {
                            idMunicipio = 104.0,
                            idDepartamento = 8.0,
                            nombre = "San Mateo Ixtatán"
                        },
                        new
                        {
                            idMunicipio = 105.0,
                            idDepartamento = 8.0,
                            nombre = "San Miguel Acatán"
                        },
                        new
                        {
                            idMunicipio = 106.0,
                            idDepartamento = 8.0,
                            nombre = "San Pedro Necta"
                        },
                        new
                        {
                            idMunicipio = 107.0,
                            idDepartamento = 8.0,
                            nombre = "San Rafael La Independencia"
                        },
                        new
                        {
                            idMunicipio = 108.0,
                            idDepartamento = 8.0,
                            nombre = "San Rafael Petzal"
                        },
                        new
                        {
                            idMunicipio = 109.0,
                            idDepartamento = 8.0,
                            nombre = "San Sebastián Coatán"
                        },
                        new
                        {
                            idMunicipio = 110.0,
                            idDepartamento = 8.0,
                            nombre = "San Sebastián Huehuetenango"
                        },
                        new
                        {
                            idMunicipio = 111.0,
                            idDepartamento = 8.0,
                            nombre = "Santa Ana Huista"
                        },
                        new
                        {
                            idMunicipio = 112.0,
                            idDepartamento = 8.0,
                            nombre = "Santa Bárbara"
                        },
                        new
                        {
                            idMunicipio = 113.0,
                            idDepartamento = 8.0,
                            nombre = "Santa Cruz Barillas"
                        },
                        new
                        {
                            idMunicipio = 114.0,
                            idDepartamento = 8.0,
                            nombre = "Santa Eulalia"
                        },
                        new
                        {
                            idMunicipio = 115.0,
                            idDepartamento = 8.0,
                            nombre = "Santiago Chimaltenango"
                        },
                        new
                        {
                            idMunicipio = 116.0,
                            idDepartamento = 8.0,
                            nombre = "Soloma"
                        },
                        new
                        {
                            idMunicipio = 117.0,
                            idDepartamento = 8.0,
                            nombre = "Tectitán"
                        },
                        new
                        {
                            idMunicipio = 118.0,
                            idDepartamento = 8.0,
                            nombre = "Todos Santos Cuchumatan"
                        },
                        new
                        {
                            idMunicipio = 119.0,
                            idDepartamento = 9.0,
                            nombre = "El Estor"
                        },
                        new
                        {
                            idMunicipio = 120.0,
                            idDepartamento = 9.0,
                            nombre = "Livingston"
                        },
                        new
                        {
                            idMunicipio = 121.0,
                            idDepartamento = 9.0,
                            nombre = "Los Amates"
                        },
                        new
                        {
                            idMunicipio = 122.0,
                            idDepartamento = 9.0,
                            nombre = "Morales"
                        },
                        new
                        {
                            idMunicipio = 123.0,
                            idDepartamento = 9.0,
                            nombre = "Puerto Barrios"
                        },
                        new
                        {
                            idMunicipio = 124.0,
                            idDepartamento = 10.0,
                            nombre = "Agua Blanca"
                        },
                        new
                        {
                            idMunicipio = 125.0,
                            idDepartamento = 10.0,
                            nombre = "Asunción Mita"
                        },
                        new
                        {
                            idMunicipio = 126.0,
                            idDepartamento = 10.0,
                            nombre = "Atescatempa"
                        },
                        new
                        {
                            idMunicipio = 127.0,
                            idDepartamento = 10.0,
                            nombre = "Comapa"
                        },
                        new
                        {
                            idMunicipio = 128.0,
                            idDepartamento = 10.0,
                            nombre = "Conguaco"
                        },
                        new
                        {
                            idMunicipio = 129.0,
                            idDepartamento = 10.0,
                            nombre = "El Adelanto"
                        },
                        new
                        {
                            idMunicipio = 130.0,
                            idDepartamento = 10.0,
                            nombre = "El Progreso"
                        },
                        new
                        {
                            idMunicipio = 131.0,
                            idDepartamento = 10.0,
                            nombre = "Jalpatagua"
                        },
                        new
                        {
                            idMunicipio = 132.0,
                            idDepartamento = 10.0,
                            nombre = "Jerez"
                        },
                        new
                        {
                            idMunicipio = 133.0,
                            idDepartamento = 10.0,
                            nombre = "Jutiapa"
                        },
                        new
                        {
                            idMunicipio = 134.0,
                            idDepartamento = 10.0,
                            nombre = "Moyuta"
                        },
                        new
                        {
                            idMunicipio = 135.0,
                            idDepartamento = 10.0,
                            nombre = "Pasaco"
                        },
                        new
                        {
                            idMunicipio = 136.0,
                            idDepartamento = 10.0,
                            nombre = "Quezada"
                        },
                        new
                        {
                            idMunicipio = 137.0,
                            idDepartamento = 10.0,
                            nombre = "San José Acatempa"
                        },
                        new
                        {
                            idMunicipio = 138.0,
                            idDepartamento = 10.0,
                            nombre = "Santa Catarina Mita"
                        },
                        new
                        {
                            idMunicipio = 139.0,
                            idDepartamento = 10.0,
                            nombre = "Yupiltepeque"
                        },
                        new
                        {
                            idMunicipio = 140.0,
                            idDepartamento = 10.0,
                            nombre = "Zapotitlán"
                        },
                        new
                        {
                            idMunicipio = 141.0,
                            idDepartamento = 11.0,
                            nombre = "Dolores"
                        },
                        new
                        {
                            idMunicipio = 142.0,
                            idDepartamento = 11.0,
                            nombre = "Flores"
                        },
                        new
                        {
                            idMunicipio = 143.0,
                            idDepartamento = 11.0,
                            nombre = "La Libertad"
                        },
                        new
                        {
                            idMunicipio = 144.0,
                            idDepartamento = 11.0,
                            nombre = "Melchor de Mencos"
                        },
                        new
                        {
                            idMunicipio = 145.0,
                            idDepartamento = 11.0,
                            nombre = "Poptún"
                        },
                        new
                        {
                            idMunicipio = 146.0,
                            idDepartamento = 11.0,
                            nombre = "San Andrés"
                        },
                        new
                        {
                            idMunicipio = 147.0,
                            idDepartamento = 11.0,
                            nombre = "San Benito"
                        },
                        new
                        {
                            idMunicipio = 148.0,
                            idDepartamento = 11.0,
                            nombre = "San Francisco"
                        },
                        new
                        {
                            idMunicipio = 149.0,
                            idDepartamento = 11.0,
                            nombre = "San José"
                        },
                        new
                        {
                            idMunicipio = 150.0,
                            idDepartamento = 11.0,
                            nombre = "San Luis"
                        },
                        new
                        {
                            idMunicipio = 151.0,
                            idDepartamento = 11.0,
                            nombre = "Santa Ana"
                        },
                        new
                        {
                            idMunicipio = 152.0,
                            idDepartamento = 11.0,
                            nombre = "Sayaxché"
                        },
                        new
                        {
                            idMunicipio = 153.0,
                            idDepartamento = 11.0,
                            nombre = "Las Cruces"
                        },
                        new
                        {
                            idMunicipio = 154.0,
                            idDepartamento = 12.0,
                            nombre = "Almolonga"
                        },
                        new
                        {
                            idMunicipio = 155.0,
                            idDepartamento = 12.0,
                            nombre = "Cabricán"
                        },
                        new
                        {
                            idMunicipio = 156.0,
                            idDepartamento = 12.0,
                            nombre = "Cajolá"
                        },
                        new
                        {
                            idMunicipio = 157.0,
                            idDepartamento = 12.0,
                            nombre = "Cantel"
                        },
                        new
                        {
                            idMunicipio = 158.0,
                            idDepartamento = 12.0,
                            nombre = "Coatepeque"
                        },
                        new
                        {
                            idMunicipio = 159.0,
                            idDepartamento = 12.0,
                            nombre = "Colomba"
                        },
                        new
                        {
                            idMunicipio = 160.0,
                            idDepartamento = 12.0,
                            nombre = "Concepción Chiquirichapa"
                        },
                        new
                        {
                            idMunicipio = 161.0,
                            idDepartamento = 12.0,
                            nombre = "El Palmar"
                        },
                        new
                        {
                            idMunicipio = 162.0,
                            idDepartamento = 12.0,
                            nombre = "Flores Costa Cuca"
                        },
                        new
                        {
                            idMunicipio = 163.0,
                            idDepartamento = 12.0,
                            nombre = "Génova"
                        },
                        new
                        {
                            idMunicipio = 164.0,
                            idDepartamento = 12.0,
                            nombre = "Huitán"
                        },
                        new
                        {
                            idMunicipio = 165.0,
                            idDepartamento = 12.0,
                            nombre = "La Esperanza"
                        },
                        new
                        {
                            idMunicipio = 166.0,
                            idDepartamento = 12.0,
                            nombre = "Olintepeque"
                        },
                        new
                        {
                            idMunicipio = 167.0,
                            idDepartamento = 12.0,
                            nombre = "Ostuncalco"
                        },
                        new
                        {
                            idMunicipio = 168.0,
                            idDepartamento = 12.0,
                            nombre = "Palestina de Los Altos"
                        },
                        new
                        {
                            idMunicipio = 169.0,
                            idDepartamento = 12.0,
                            nombre = "Quetzaltenango"
                        },
                        new
                        {
                            idMunicipio = 170.0,
                            idDepartamento = 12.0,
                            nombre = "Salcajá"
                        },
                        new
                        {
                            idMunicipio = 171.0,
                            idDepartamento = 12.0,
                            nombre = "San Carlos Sija"
                        },
                        new
                        {
                            idMunicipio = 172.0,
                            idDepartamento = 12.0,
                            nombre = "San Francisco La Unión"
                        },
                        new
                        {
                            idMunicipio = 173.0,
                            idDepartamento = 12.0,
                            nombre = "San Martín Sacatepéquez"
                        },
                        new
                        {
                            idMunicipio = 174.0,
                            idDepartamento = 12.0,
                            nombre = "San Mateo"
                        },
                        new
                        {
                            idMunicipio = 175.0,
                            idDepartamento = 12.0,
                            nombre = "San Miguel Sigüilá"
                        },
                        new
                        {
                            idMunicipio = 176.0,
                            idDepartamento = 12.0,
                            nombre = "Sibilia"
                        },
                        new
                        {
                            idMunicipio = 177.0,
                            idDepartamento = 12.0,
                            nombre = "Zunil"
                        },
                        new
                        {
                            idMunicipio = 178.0,
                            idDepartamento = 13.0,
                            nombre = "Canillá"
                        },
                        new
                        {
                            idMunicipio = 179.0,
                            idDepartamento = 13.0,
                            nombre = "Chajul"
                        },
                        new
                        {
                            idMunicipio = 180.0,
                            idDepartamento = 13.0,
                            nombre = "Chicamán"
                        },
                        new
                        {
                            idMunicipio = 181.0,
                            idDepartamento = 13.0,
                            nombre = "Chiché"
                        },
                        new
                        {
                            idMunicipio = 182.0,
                            idDepartamento = 13.0,
                            nombre = "Chichicastenango"
                        },
                        new
                        {
                            idMunicipio = 183.0,
                            idDepartamento = 13.0,
                            nombre = "Chinique"
                        },
                        new
                        {
                            idMunicipio = 184.0,
                            idDepartamento = 13.0,
                            nombre = "Cunén"
                        },
                        new
                        {
                            idMunicipio = 185.0,
                            idDepartamento = 13.0,
                            nombre = "Ixcán"
                        },
                        new
                        {
                            idMunicipio = 186.0,
                            idDepartamento = 13.0,
                            nombre = "Joyabaj"
                        },
                        new
                        {
                            idMunicipio = 187.0,
                            idDepartamento = 13.0,
                            nombre = "Nebaj"
                        },
                        new
                        {
                            idMunicipio = 188.0,
                            idDepartamento = 13.0,
                            nombre = "Pachalum"
                        },
                        new
                        {
                            idMunicipio = 189.0,
                            idDepartamento = 13.0,
                            nombre = "Patzité"
                        },
                        new
                        {
                            idMunicipio = 190.0,
                            idDepartamento = 13.0,
                            nombre = "Sacapulas"
                        },
                        new
                        {
                            idMunicipio = 191.0,
                            idDepartamento = 13.0,
                            nombre = "San Andrés Sajcabajá"
                        },
                        new
                        {
                            idMunicipio = 192.0,
                            idDepartamento = 13.0,
                            nombre = "San Antonio Ilotenango"
                        },
                        new
                        {
                            idMunicipio = 193.0,
                            idDepartamento = 13.0,
                            nombre = "San Bartolomé Jocotenango"
                        },
                        new
                        {
                            idMunicipio = 194.0,
                            idDepartamento = 13.0,
                            nombre = "San Juan Cotzal"
                        },
                        new
                        {
                            idMunicipio = 195.0,
                            idDepartamento = 13.0,
                            nombre = "San Pedro Jocopilas"
                        },
                        new
                        {
                            idMunicipio = 196.0,
                            idDepartamento = 13.0,
                            nombre = "Santa Cruz del Quiché"
                        },
                        new
                        {
                            idMunicipio = 197.0,
                            idDepartamento = 13.0,
                            nombre = "Uspantán"
                        },
                        new
                        {
                            idMunicipio = 198.0,
                            idDepartamento = 13.0,
                            nombre = "Zacualpa"
                        },
                        new
                        {
                            idMunicipio = 199.0,
                            idDepartamento = 14.0,
                            nombre = "Champerico"
                        },
                        new
                        {
                            idMunicipio = 200.0,
                            idDepartamento = 14.0,
                            nombre = "El Asintal"
                        },
                        new
                        {
                            idMunicipio = 201.0,
                            idDepartamento = 14.0,
                            nombre = "Nuevo San Carlos"
                        },
                        new
                        {
                            idMunicipio = 202.0,
                            idDepartamento = 14.0,
                            nombre = "Retalhuleu"
                        },
                        new
                        {
                            idMunicipio = 203.0,
                            idDepartamento = 14.0,
                            nombre = "San Andrés Villa Seca"
                        },
                        new
                        {
                            idMunicipio = 204.0,
                            idDepartamento = 14.0,
                            nombre = "San Felipe"
                        },
                        new
                        {
                            idMunicipio = 205.0,
                            idDepartamento = 14.0,
                            nombre = "San Martín Zapotitlán"
                        },
                        new
                        {
                            idMunicipio = 206.0,
                            idDepartamento = 14.0,
                            nombre = "San Sebastián"
                        },
                        new
                        {
                            idMunicipio = 207.0,
                            idDepartamento = 14.0,
                            nombre = "Santa Cruz Muluá"
                        },
                        new
                        {
                            idMunicipio = 208.0,
                            idDepartamento = 15.0,
                            nombre = "Alotenango"
                        },
                        new
                        {
                            idMunicipio = 209.0,
                            idDepartamento = 15.0,
                            nombre = "Antigua"
                        },
                        new
                        {
                            idMunicipio = 210.0,
                            idDepartamento = 15.0,
                            nombre = "Ciudad Vieja"
                        },
                        new
                        {
                            idMunicipio = 211.0,
                            idDepartamento = 15.0,
                            nombre = "Jocotenango"
                        },
                        new
                        {
                            idMunicipio = 212.0,
                            idDepartamento = 15.0,
                            nombre = "Magdalena Milpas Altas"
                        },
                        new
                        {
                            idMunicipio = 213.0,
                            idDepartamento = 15.0,
                            nombre = "Pastores"
                        },
                        new
                        {
                            idMunicipio = 214.0,
                            idDepartamento = 15.0,
                            nombre = "San Antonio Aguas Calientes"
                        },
                        new
                        {
                            idMunicipio = 215.0,
                            idDepartamento = 15.0,
                            nombre = "San Bartolomé Milpas Altas"
                        },
                        new
                        {
                            idMunicipio = 216.0,
                            idDepartamento = 15.0,
                            nombre = "San Lucas Sacatepéquez"
                        },
                        new
                        {
                            idMunicipio = 217.0,
                            idDepartamento = 15.0,
                            nombre = "San Miguel Dueñas"
                        },
                        new
                        {
                            idMunicipio = 218.0,
                            idDepartamento = 15.0,
                            nombre = "Santa Catarina Barahona"
                        },
                        new
                        {
                            idMunicipio = 219.0,
                            idDepartamento = 15.0,
                            nombre = "Santa Lucía Milpas Altas"
                        },
                        new
                        {
                            idMunicipio = 220.0,
                            idDepartamento = 15.0,
                            nombre = "Santa María de Jesús"
                        },
                        new
                        {
                            idMunicipio = 221.0,
                            idDepartamento = 15.0,
                            nombre = "Santiago Sacatepéquez"
                        },
                        new
                        {
                            idMunicipio = 222.0,
                            idDepartamento = 15.0,
                            nombre = "Santo Domingo Xenacoj"
                        },
                        new
                        {
                            idMunicipio = 223.0,
                            idDepartamento = 15.0,
                            nombre = "Sumpango"
                        },
                        new
                        {
                            idMunicipio = 224.0,
                            idDepartamento = 16.0,
                            nombre = "Ayutla"
                        },
                        new
                        {
                            idMunicipio = 225.0,
                            idDepartamento = 16.0,
                            nombre = "Catarina"
                        },
                        new
                        {
                            idMunicipio = 226.0,
                            idDepartamento = 16.0,
                            nombre = "Comitancillo"
                        },
                        new
                        {
                            idMunicipio = 227.0,
                            idDepartamento = 16.0,
                            nombre = "Concepción Tutuapa"
                        },
                        new
                        {
                            idMunicipio = 228.0,
                            idDepartamento = 16.0,
                            nombre = "El Quetzal"
                        },
                        new
                        {
                            idMunicipio = 229.0,
                            idDepartamento = 16.0,
                            nombre = "El Rodeo"
                        },
                        new
                        {
                            idMunicipio = 230.0,
                            idDepartamento = 16.0,
                            nombre = "El Tumbador"
                        },
                        new
                        {
                            idMunicipio = 231.0,
                            idDepartamento = 16.0,
                            nombre = "Esquipulas Palo Gordo"
                        },
                        new
                        {
                            idMunicipio = 232.0,
                            idDepartamento = 16.0,
                            nombre = "Ixchiguan"
                        },
                        new
                        {
                            idMunicipio = 233.0,
                            idDepartamento = 16.0,
                            nombre = "La Reforma"
                        },
                        new
                        {
                            idMunicipio = 234.0,
                            idDepartamento = 16.0,
                            nombre = "Malacatán"
                        },
                        new
                        {
                            idMunicipio = 235.0,
                            idDepartamento = 16.0,
                            nombre = "Nuevo Progreso"
                        },
                        new
                        {
                            idMunicipio = 236.0,
                            idDepartamento = 16.0,
                            nombre = "Ocos"
                        },
                        new
                        {
                            idMunicipio = 237.0,
                            idDepartamento = 16.0,
                            nombre = "Pajapita"
                        },
                        new
                        {
                            idMunicipio = 238.0,
                            idDepartamento = 16.0,
                            nombre = "Río Blanco"
                        },
                        new
                        {
                            idMunicipio = 239.0,
                            idDepartamento = 16.0,
                            nombre = "San Antonio Sacatepéquez"
                        },
                        new
                        {
                            idMunicipio = 240.0,
                            idDepartamento = 16.0,
                            nombre = "San Cristóbal Cucho"
                        },
                        new
                        {
                            idMunicipio = 241.0,
                            idDepartamento = 16.0,
                            nombre = "San José Ojetenam"
                        },
                        new
                        {
                            idMunicipio = 242.0,
                            idDepartamento = 16.0,
                            nombre = "San Lorenzo"
                        },
                        new
                        {
                            idMunicipio = 243.0,
                            idDepartamento = 16.0,
                            nombre = "San Marcos"
                        },
                        new
                        {
                            idMunicipio = 244.0,
                            idDepartamento = 16.0,
                            nombre = "San Miguel Ixtahuacán"
                        },
                        new
                        {
                            idMunicipio = 245.0,
                            idDepartamento = 16.0,
                            nombre = "San Pablo"
                        },
                        new
                        {
                            idMunicipio = 246.0,
                            idDepartamento = 16.0,
                            nombre = "San Pedro Sacatepéquez"
                        },
                        new
                        {
                            idMunicipio = 247.0,
                            idDepartamento = 16.0,
                            nombre = "San Rafael Pie de La Cuesta"
                        },
                        new
                        {
                            idMunicipio = 248.0,
                            idDepartamento = 16.0,
                            nombre = "San Sibinal"
                        },
                        new
                        {
                            idMunicipio = 249.0,
                            idDepartamento = 16.0,
                            nombre = "Sipacapa"
                        },
                        new
                        {
                            idMunicipio = 250.0,
                            idDepartamento = 16.0,
                            nombre = "Tacaná"
                        },
                        new
                        {
                            idMunicipio = 251.0,
                            idDepartamento = 16.0,
                            nombre = "Tajumulco"
                        },
                        new
                        {
                            idMunicipio = 252.0,
                            idDepartamento = 16.0,
                            nombre = "Tejutla"
                        },
                        new
                        {
                            idMunicipio = 253.0,
                            idDepartamento = 17.0,
                            nombre = "Barberena"
                        },
                        new
                        {
                            idMunicipio = 254.0,
                            idDepartamento = 17.0,
                            nombre = "Casillas"
                        },
                        new
                        {
                            idMunicipio = 255.0,
                            idDepartamento = 17.0,
                            nombre = "Chiquimulilla"
                        },
                        new
                        {
                            idMunicipio = 256.0,
                            idDepartamento = 17.0,
                            nombre = "Cuilapa"
                        },
                        new
                        {
                            idMunicipio = 257.0,
                            idDepartamento = 17.0,
                            nombre = "Guazacapán"
                        },
                        new
                        {
                            idMunicipio = 258.0,
                            idDepartamento = 17.0,
                            nombre = "Nueva Santa Rosa"
                        },
                        new
                        {
                            idMunicipio = 259.0,
                            idDepartamento = 17.0,
                            nombre = "Oratorio"
                        },
                        new
                        {
                            idMunicipio = 260.0,
                            idDepartamento = 17.0,
                            nombre = "Pueblo Nuevo Viñas"
                        },
                        new
                        {
                            idMunicipio = 261.0,
                            idDepartamento = 17.0,
                            nombre = "San Juan Tecuaco"
                        },
                        new
                        {
                            idMunicipio = 262.0,
                            idDepartamento = 17.0,
                            nombre = "San Rafael Las Flores"
                        },
                        new
                        {
                            idMunicipio = 263.0,
                            idDepartamento = 17.0,
                            nombre = "Santa Cruz Naranjo"
                        },
                        new
                        {
                            idMunicipio = 264.0,
                            idDepartamento = 17.0,
                            nombre = "Santa María Ixhuatán"
                        },
                        new
                        {
                            idMunicipio = 265.0,
                            idDepartamento = 17.0,
                            nombre = "Santa Rosa de Lima"
                        },
                        new
                        {
                            idMunicipio = 266.0,
                            idDepartamento = 17.0,
                            nombre = "Taxisco"
                        },
                        new
                        {
                            idMunicipio = 267.0,
                            idDepartamento = 18.0,
                            nombre = "Concepción"
                        },
                        new
                        {
                            idMunicipio = 268.0,
                            idDepartamento = 18.0,
                            nombre = "Nahualá"
                        },
                        new
                        {
                            idMunicipio = 269.0,
                            idDepartamento = 18.0,
                            nombre = "Panajachel"
                        },
                        new
                        {
                            idMunicipio = 270.0,
                            idDepartamento = 18.0,
                            nombre = "San Andrés Semetabaj"
                        },
                        new
                        {
                            idMunicipio = 271.0,
                            idDepartamento = 18.0,
                            nombre = "San Antonio Palopó"
                        },
                        new
                        {
                            idMunicipio = 272.0,
                            idDepartamento = 18.0,
                            nombre = "San José Chacaya"
                        },
                        new
                        {
                            idMunicipio = 273.0,
                            idDepartamento = 18.0,
                            nombre = "San Juan La Laguna"
                        },
                        new
                        {
                            idMunicipio = 274.0,
                            idDepartamento = 18.0,
                            nombre = "San Lucas Tolimán"
                        },
                        new
                        {
                            idMunicipio = 275.0,
                            idDepartamento = 18.0,
                            nombre = "San Marcos La Laguna"
                        },
                        new
                        {
                            idMunicipio = 276.0,
                            idDepartamento = 18.0,
                            nombre = "San Pablo La Laguna"
                        },
                        new
                        {
                            idMunicipio = 277.0,
                            idDepartamento = 18.0,
                            nombre = "San Pedro La Laguna"
                        },
                        new
                        {
                            idMunicipio = 278.0,
                            idDepartamento = 18.0,
                            nombre = "Santa Catarina Ixtahuacan"
                        },
                        new
                        {
                            idMunicipio = 279.0,
                            idDepartamento = 18.0,
                            nombre = "Santa Catarina Palopó"
                        },
                        new
                        {
                            idMunicipio = 280.0,
                            idDepartamento = 18.0,
                            nombre = "Santa Clara La Laguna"
                        },
                        new
                        {
                            idMunicipio = 281.0,
                            idDepartamento = 18.0,
                            nombre = "Santa Cruz La Laguna"
                        },
                        new
                        {
                            idMunicipio = 282.0,
                            idDepartamento = 18.0,
                            nombre = "Santa Lucía Utatlán"
                        },
                        new
                        {
                            idMunicipio = 283.0,
                            idDepartamento = 18.0,
                            nombre = "Santa María Visitación"
                        },
                        new
                        {
                            idMunicipio = 284.0,
                            idDepartamento = 18.0,
                            nombre = "Santiago Atitlán"
                        },
                        new
                        {
                            idMunicipio = 285.0,
                            idDepartamento = 18.0,
                            nombre = "Sololá"
                        },
                        new
                        {
                            idMunicipio = 286.0,
                            idDepartamento = 19.0,
                            nombre = "Chicacao"
                        },
                        new
                        {
                            idMunicipio = 287.0,
                            idDepartamento = 19.0,
                            nombre = "Cuyotenango"
                        },
                        new
                        {
                            idMunicipio = 288.0,
                            idDepartamento = 19.0,
                            nombre = "Mazatenango"
                        },
                        new
                        {
                            idMunicipio = 289.0,
                            idDepartamento = 19.0,
                            nombre = "Patulul"
                        },
                        new
                        {
                            idMunicipio = 290.0,
                            idDepartamento = 19.0,
                            nombre = "Pueblo Nuevo"
                        },
                        new
                        {
                            idMunicipio = 291.0,
                            idDepartamento = 19.0,
                            nombre = "Río Bravo"
                        },
                        new
                        {
                            idMunicipio = 292.0,
                            idDepartamento = 19.0,
                            nombre = "Samayac"
                        },
                        new
                        {
                            idMunicipio = 293.0,
                            idDepartamento = 19.0,
                            nombre = "San Antonio Suchitepéquez"
                        },
                        new
                        {
                            idMunicipio = 294.0,
                            idDepartamento = 19.0,
                            nombre = "San Bernardino"
                        },
                        new
                        {
                            idMunicipio = 295.0,
                            idDepartamento = 19.0,
                            nombre = "San Francisco Zapotitlán"
                        },
                        new
                        {
                            idMunicipio = 296.0,
                            idDepartamento = 19.0,
                            nombre = "San Gabriel"
                        },
                        new
                        {
                            idMunicipio = 297.0,
                            idDepartamento = 19.0,
                            nombre = "San José El Idolo"
                        },
                        new
                        {
                            idMunicipio = 298.0,
                            idDepartamento = 19.0,
                            nombre = "San Juan Bautista"
                        },
                        new
                        {
                            idMunicipio = 299.0,
                            idDepartamento = 19.0,
                            nombre = "San Lorenzo"
                        },
                        new
                        {
                            idMunicipio = 300.0,
                            idDepartamento = 19.0,
                            nombre = "San Miguel Panán"
                        },
                        new
                        {
                            idMunicipio = 301.0,
                            idDepartamento = 19.0,
                            nombre = "San Pablo Jocopilas"
                        },
                        new
                        {
                            idMunicipio = 302.0,
                            idDepartamento = 19.0,
                            nombre = "Santa Bárbara"
                        },
                        new
                        {
                            idMunicipio = 303.0,
                            idDepartamento = 19.0,
                            nombre = "Santo Domingo Suchitepequez"
                        },
                        new
                        {
                            idMunicipio = 304.0,
                            idDepartamento = 19.0,
                            nombre = "Santo Tomas La Unión"
                        },
                        new
                        {
                            idMunicipio = 305.0,
                            idDepartamento = 19.0,
                            nombre = "Zunilito"
                        },
                        new
                        {
                            idMunicipio = 306.0,
                            idDepartamento = 20.0,
                            nombre = "Momostenango"
                        },
                        new
                        {
                            idMunicipio = 307.0,
                            idDepartamento = 20.0,
                            nombre = "San Andrés Xecul"
                        },
                        new
                        {
                            idMunicipio = 308.0,
                            idDepartamento = 20.0,
                            nombre = "San Bartolo"
                        },
                        new
                        {
                            idMunicipio = 309.0,
                            idDepartamento = 20.0,
                            nombre = "San Cristóbal Totonicapán"
                        },
                        new
                        {
                            idMunicipio = 310.0,
                            idDepartamento = 20.0,
                            nombre = "San Francisco El Alto"
                        },
                        new
                        {
                            idMunicipio = 311.0,
                            idDepartamento = 20.0,
                            nombre = "Santa Lucía La Reforma"
                        },
                        new
                        {
                            idMunicipio = 312.0,
                            idDepartamento = 20.0,
                            nombre = "Santa María Chiquimula"
                        },
                        new
                        {
                            idMunicipio = 313.0,
                            idDepartamento = 20.0,
                            nombre = "Totonicapán"
                        },
                        new
                        {
                            idMunicipio = 314.0,
                            idDepartamento = 20.0,
                            nombre = "San"
                        },
                        new
                        {
                            idMunicipio = 315.0,
                            idDepartamento = 21.0,
                            nombre = "Cabañas"
                        },
                        new
                        {
                            idMunicipio = 316.0,
                            idDepartamento = 21.0,
                            nombre = "Estanzuela"
                        },
                        new
                        {
                            idMunicipio = 317.0,
                            idDepartamento = 21.0,
                            nombre = "Gualán"
                        },
                        new
                        {
                            idMunicipio = 318.0,
                            idDepartamento = 21.0,
                            nombre = "Huité"
                        },
                        new
                        {
                            idMunicipio = 319.0,
                            idDepartamento = 21.0,
                            nombre = "La Unión"
                        },
                        new
                        {
                            idMunicipio = 320.0,
                            idDepartamento = 21.0,
                            nombre = "Río Hondo"
                        },
                        new
                        {
                            idMunicipio = 321.0,
                            idDepartamento = 21.0,
                            nombre = "San Diego"
                        },
                        new
                        {
                            idMunicipio = 322.0,
                            idDepartamento = 21.0,
                            nombre = "Teculután"
                        },
                        new
                        {
                            idMunicipio = 323.0,
                            idDepartamento = 21.0,
                            nombre = "Usumatlán"
                        },
                        new
                        {
                            idMunicipio = 324.0,
                            idDepartamento = 21.0,
                            nombre = "Zacapa"
                        },
                        new
                        {
                            idMunicipio = 325.0,
                            idDepartamento = 22.0,
                            nombre = "Jalapa"
                        },
                        new
                        {
                            idMunicipio = 326.0,
                            idDepartamento = 22.0,
                            nombre = "Mataquescuintla"
                        },
                        new
                        {
                            idMunicipio = 327.0,
                            idDepartamento = 22.0,
                            nombre = "Monjas"
                        },
                        new
                        {
                            idMunicipio = 328.0,
                            idDepartamento = 22.0,
                            nombre = "San Carlos Alzatate"
                        },
                        new
                        {
                            idMunicipio = 329.0,
                            idDepartamento = 22.0,
                            nombre = "San Luis Jilotepeque"
                        },
                        new
                        {
                            idMunicipio = 330.0,
                            idDepartamento = 22.0,
                            nombre = "San Pedro Pinula"
                        },
                        new
                        {
                            idMunicipio = 331.0,
                            idDepartamento = 22.0,
                            nombre = "San Manuel Chaparrón"
                        },
                        new
                        {
                            idMunicipio = 332.0,
                            idDepartamento = 5.0,
                            nombre = "Sansare"
                        },
                        new
                        {
                            idMunicipio = 333.0,
                            idDepartamento = 6.0,
                            nombre = "Guanagazapa"
                        },
                        new
                        {
                            idMunicipio = 334.0,
                            idDepartamento = 6.0,
                            nombre = "Sipacate"
                        },
                        new
                        {
                            idMunicipio = 335.0,
                            idDepartamento = 7.0,
                            nombre = "Villa Nueva"
                        },
                        new
                        {
                            idMunicipio = 336.0,
                            idDepartamento = 8.0,
                            nombre = "Petatán"
                        },
                        new
                        {
                            idMunicipio = 337.0,
                            idDepartamento = 8.0,
                            nombre = "San Ildefonso Ixtahuacán"
                        },
                        new
                        {
                            idMunicipio = 338.0,
                            idDepartamento = 11.0,
                            nombre = "El Chal"
                        },
                        new
                        {
                            idMunicipio = 339.0,
                            idDepartamento = 16.0,
                            nombre = "La Blanca"
                        },
                        new
                        {
                            idMunicipio = 340.0,
                            idDepartamento = 19.0,
                            nombre = "San José La Máquina"
                        });
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Pais", b =>
                {
                    b.Property<double>("idPais");

                    b.Property<string>("nombre");

                    b.HasKey("idPais");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            idPais = 1.0,
                            nombre = "Guatemala"
                        });
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Persona", b =>
                {
                    b.Property<double>("idPersona");

                    b.Property<string>("escolaridad");

                    b.Property<DateTime>("fechaNacimiento");

                    b.Property<string>("grupoEtnico");

                    b.Property<double>("idDomicilio");

                    b.Property<double>("idResidencia");

                    b.Property<string>("primerApellido");

                    b.Property<string>("primerNombre");

                    b.Property<string>("religion");

                    b.Property<string>("segundoApellido");

                    b.Property<string>("segundoNombre");

                    b.Property<bool>("sexo");

                    b.HasKey("idPersona");

                    b.HasIndex("idDomicilio");

                    b.HasIndex("idResidencia");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Telefono", b =>
                {
                    b.Property<double>("idTelefono");

                    b.Property<bool>("estaHabilitado");

                    b.Property<DateTime>("fechaRegistro");

                    b.Property<double>("idPersona");

                    b.Property<string>("telefono");

                    b.HasKey("idTelefono");

                    b.HasIndex("idPersona");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Correo", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaidPersona");
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Departamento", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Pais", "pais")
                        .WithMany("departamentos")
                        .HasForeignKey("idPais")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Direccion", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Municipio", "municipio")
                        .WithMany("direcciones")
                        .HasForeignKey("idMunicipio")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Municipio", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Departamento")
                        .WithMany("municipios")
                        .HasForeignKey("idDepartamento")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Persona", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Direccion", "domicilio")
                        .WithMany()
                        .HasForeignKey("idDomicilio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityModelFundabien.entities.Direccion", "residencia")
                        .WithMany()
                        .HasForeignKey("idResidencia")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityModelFundabien.entities.Telefono", b =>
                {
                    b.HasOne("EntityModelFundabien.entities.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("idPersona")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
